# Generated by Django 2.1 on 2019-10-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.CharField(max_length=80)),
                ('warranty', models.CharField(max_length=80)),
                ('model_number', models.CharField(max_length=80)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
            ],
        ),
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Catagories',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='catagories',
            old_name='catagoryimage',
            new_name='catagory_image',
        ),
        migrations.RenameField(
            model_name='catagories',
            old_name='catagoryname',
            new_name='catagory_name',
        ),
    ]
